#!/usr/bin/env python
import sys
from hs110_exporter.http import start_http_server

if __name__ == '__main__':
  if len(sys.argv) not in [1, 2]:
    print "Usage: h110_exporter [port]"
    sys.exit(1)

  if len(sys.argv) == 2:
    port = int(sys.argv[1])
  else:
    port = 9498 

  start_http_server( port )

